# 参考：https://skychang.github.io/2017/01/01/Hexo-Use_Travis_CI_Auto_Deploy_Blog/
language:  node_js
node_js:  stable
script:
  -  npm  install
  -  hexo  cl
after_success:
  -  git  config  --global  user.name  "Trumeet" 
  -  git  config  --global  user.email  "liangyuteng12345@gmail.com"
  -  sed  -i''  "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~"  _config.yml
  -  hexo  deploy  -g
